pki:
  ca: /ca.crt
  cert: /host3.crt
  key: /host3.key

static_host_map:
  "192.168.100.1": ["172.17.0.2:4242"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "192.168.100.1"

listen:
  host: 0.0.0.0
  port: 4242

tun:
  dev: nebula1

firewall:
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
