pki:
  ca: /ca.crt
  cert: /lighthouse1.crt
  key: /lighthouse1.key

lighthouse:
  am_lighthouse: true

listen:
  host: 0.0.0.0
  port: 4242

tun:
  dev: nebula1

firewall:
  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: any
      host: any
